 
****************************************
Report : resources
Design : RRT_TOP
Version: T-2022.03
Date   : Mon Jul 13 01:43:54 2026
****************************************


Resource Report for this hierarchy in file
        /RAID2/LAB/icssl/icsslRA27/RTL_Project/01_RTL/PE.sv
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| lt_x_10        | DW_cmp         | width=4    | u_PE0/lt_196 (PE.sv:196)   |
| gt_x_14        | DW_cmp         | width=8    | u_PE0/gt_221 (PE.sv:221)   |
| gt_x_15        | DW_cmp         | width=8    | u_PE0/gt_222 (PE.sv:222)   |
| gt_x_16        | DW_cmp         | width=8    | u_PE0/gt_223 (PE.sv:223)   |
| lt_x_17        | DW_cmp         | width=10   | u_PE0/lt_227 (PE.sv:227)   |
| lt_x_24        | DW_cmp         | width=4    | u_PE0/lt_263 (PE.sv:263)   |
| add_x_25       | DW01_inc       | width=4    | u_PE0/add_263 (PE.sv:263)  |
| add_x_27       | DW01_inc       | width=6    | u_PE0/add_108_C314 (PE.sv:108) |
| gt_x_29        | DW_cmp         | width=6    | u_PE0/gt_110_C314 (PE.sv:110) |
| add_x_30       | DW01_inc       | width=6    | u_PE0/add_108_C335 (PE.sv:108) |
| gt_x_32        | DW_cmp         | width=6    | u_PE0/gt_110_C335 (PE.sv:110) |
| gt_x_69        | DW_cmp         | width=11   | u_PE0/gt_399 (PE.sv:399)   |
| lt_x_70        | DW_cmp         | width=11   | u_PE0/lt_400 (PE.sv:400)   |
| gt_x_71        | DW_cmp         | width=11   | u_PE0/gt_401 (PE.sv:401)   |
| gt_x_72        | DW_cmp         | width=11   | u_PE0/gt_401_2 (PE.sv:401) |
| add_x_73       | DW01_inc       | width=3    | u_PE0/add_464_S2 (PE.sv:464) |
| lt_x_98        | DW_cmp         | width=4    | u_PE2/lt_196 (PE.sv:196)   |
| gt_x_102       | DW_cmp         | width=8    | u_PE2/gt_221 (PE.sv:221)   |
| gt_x_103       | DW_cmp         | width=8    | u_PE2/gt_222 (PE.sv:222)   |
| gt_x_104       | DW_cmp         | width=8    | u_PE2/gt_223 (PE.sv:223)   |
| lt_x_105       | DW_cmp         | width=10   | u_PE2/lt_227 (PE.sv:227)   |
| lt_x_112       | DW_cmp         | width=4    | u_PE2/lt_263 (PE.sv:263)   |
| add_x_113      | DW01_inc       | width=4    | u_PE2/add_263 (PE.sv:263)  |
| add_x_117      | DW01_inc       | width=6    | u_PE2/add_108_C343 (PE.sv:108) |
| gt_x_119       | DW_cmp         | width=6    | u_PE2/gt_110_C343 (PE.sv:110) |
| add_x_120      | DW01_inc       | width=6    | u_PE2/add_108_C344 (PE.sv:108) |
| gt_x_122       | DW_cmp         | width=6    | u_PE2/gt_110_C344 (PE.sv:110) |
| add_x_123      | DW01_inc       | width=6    | u_PE2/add_108_C345 (PE.sv:108) |
| gt_x_125       | DW_cmp         | width=6    | u_PE2/gt_110_C345 (PE.sv:110) |
| gt_x_162       | DW_cmp         | width=11   | u_PE2/gt_399 (PE.sv:399)   |
| lt_x_163       | DW_cmp         | width=11   | u_PE2/lt_400 (PE.sv:400)   |
| gt_x_164       | DW_cmp         | width=11   | u_PE2/gt_401 (PE.sv:401)   |
| gt_x_165       | DW_cmp         | width=11   | u_PE2/gt_401_2 (PE.sv:401) |
| add_x_166      | DW01_inc       | width=3    | u_PE2/add_464_S2 (PE.sv:464) |
| sub_x_196      | DW01_dec       | width=2    | u_MC/sub_106_S2 (MAPCONT.sv:106) |
| gt_x_197       | DW_cmp         | width=4    | u_CC/gt_87_C92 (connection_check.sv:87) |
| sub_x_198      | DW01_sub       | width=4    | u_CC/sub_87_C92_aco (connection_check.sv:87) |
| gt_x_199       | DW_cmp         | width=4    | u_CC/gt_87_C93 (connection_check.sv:87) |
| sub_x_200      | DW01_sub       | width=4    | u_CC/sub_87_C93_aco (connection_check.sv:87) |
| gt_x_201       | DW_cmp         | width=4    | u_CC/gt_87_C94 (connection_check.sv:87) |
| sub_x_202      | DW01_sub       | width=4    | u_CC/sub_87_C94_aco (connection_check.sv:87) |
| lt_x_203       | DW_cmp         | width=4    | u_CC/lt_90_C95 (connection_check.sv:90) |
| add_x_204      | DW01_inc       | width=4    | u_CC/add_90_C95 (connection_check.sv:90) |
| lt_x_206       | DW_cmp         | width=4    | u_CC/lt_90_C96 (connection_check.sv:90) |
| add_x_207      | DW01_inc       | width=4    | u_CC/add_90_C96 (connection_check.sv:90) |
| lt_x_209       | DW_cmp         | width=4    | u_CC/lt_90_C97 (connection_check.sv:90) |
| add_x_210      | DW01_inc       | width=4    | u_CC/add_90_C97 (connection_check.sv:90) |
| lt_x_213       | DW_cmp         | width=4    | u_CC/lt_107 (connection_check.sv:107) |
| gte_x_215      | DW_cmp         | width=4    | u_CC/gte_108 (connection_check.sv:108) |
| gte_x_216      | DW_cmp         | width=8    | u_CC/gte_101_S2_C109 (connection_check.sv:101) |
| lte_x_217      | DW_cmp         | width=8    | u_CC/lte_101_S3_C109 (connection_check.sv:101) |
| gte_x_218      | DW_cmp         | width=8    | u_CC/gte_101_S2_C109_2 (connection_check.sv:101) |
| lte_x_219      | DW_cmp         | width=8    | u_CC/lte_101_S3_C109_2 (connection_check.sv:101) |
| gte_x_220      | DW_cmp         | width=8    | u_CC/gte_101_S2_C109_3 (connection_check.sv:101) |
| lte_x_221      | DW_cmp         | width=8    | u_CC/lte_101_S3_C109_3 (connection_check.sv:101) |
| lt_x_236       | DW_cmp         | width=4    | u_CC/lt_159 (connection_check.sv:159) |
| add_x_244      | DW01_inc       | width=2    | u_CC/add_222_S2 (connection_check.sv:222) |
| add_x_246      | DW01_inc       | width=4    | u_CC/add_279 (connection_check.sv:279) |
| add_x_247      | DW01_inc       | width=4    | u_CC/add_283 (connection_check.sv:283) |
| add_x_248      | DW01_inc       | width=4    | u_CC/add_286_S2 (connection_check.sv:286) |
| lt_x_305       | DW_cmp         | width=4    | u_PE1/lt_196 (PE.sv:196)   |
| gt_x_309       | DW_cmp         | width=8    | u_PE1/gt_221 (PE.sv:221)   |
| gt_x_310       | DW_cmp         | width=8    | u_PE1/gt_222 (PE.sv:222)   |
| gt_x_311       | DW_cmp         | width=8    | u_PE1/gt_223 (PE.sv:223)   |
| lt_x_312       | DW_cmp         | width=10   | u_PE1/lt_227 (PE.sv:227)   |
| lt_x_319       | DW_cmp         | width=4    | u_PE1/lt_263 (PE.sv:263)   |
| add_x_320      | DW01_inc       | width=4    | u_PE1/add_263 (PE.sv:263)  |
| add_x_322      | DW01_inc       | width=6    | u_PE1/add_108_C314 (PE.sv:108) |
| gt_x_324       | DW_cmp         | width=6    | u_PE1/gt_110_C314 (PE.sv:110) |
| add_x_325      | DW01_inc       | width=6    | u_PE1/add_108_C335 (PE.sv:108) |
| gt_x_327       | DW_cmp         | width=6    | u_PE1/gt_110_C335 (PE.sv:110) |
| gt_x_364       | DW_cmp         | width=11   | u_PE1/gt_399 (PE.sv:399)   |
| lt_x_365       | DW_cmp         | width=11   | u_PE1/lt_400 (PE.sv:400)   |
| gt_x_366       | DW_cmp         | width=11   | u_PE1/gt_401 (PE.sv:401)   |
| gt_x_367       | DW_cmp         | width=11   | u_PE1/gt_401_2 (PE.sv:401) |
| add_x_368      | DW01_inc       | width=3    | u_PE1/add_464_S2 (PE.sv:464) |
| lt_x_393       | DW_cmp         | width=4    | u_PE3/lt_196 (PE.sv:196)   |
| gt_x_397       | DW_cmp         | width=8    | u_PE3/gt_221 (PE.sv:221)   |
| gt_x_398       | DW_cmp         | width=8    | u_PE3/gt_222 (PE.sv:222)   |
| gt_x_399       | DW_cmp         | width=8    | u_PE3/gt_223 (PE.sv:223)   |
| lt_x_400       | DW_cmp         | width=10   | u_PE3/lt_227 (PE.sv:227)   |
| lt_x_407       | DW_cmp         | width=4    | u_PE3/lt_263 (PE.sv:263)   |
| add_x_408      | DW01_inc       | width=4    | u_PE3/add_263 (PE.sv:263)  |
| add_x_412      | DW01_inc       | width=6    | u_PE3/add_108_C343 (PE.sv:108) |
| gt_x_414       | DW_cmp         | width=6    | u_PE3/gt_110_C343 (PE.sv:110) |
| add_x_415      | DW01_inc       | width=6    | u_PE3/add_108_C344 (PE.sv:108) |
| gt_x_417       | DW_cmp         | width=6    | u_PE3/gt_110_C344 (PE.sv:110) |
| add_x_418      | DW01_inc       | width=6    | u_PE3/add_108_C345 (PE.sv:108) |
| gt_x_420       | DW_cmp         | width=6    | u_PE3/gt_110_C345 (PE.sv:110) |
| gt_x_457       | DW_cmp         | width=11   | u_PE3/gt_399 (PE.sv:399)   |
| lt_x_458       | DW_cmp         | width=11   | u_PE3/lt_400 (PE.sv:400)   |
| gt_x_459       | DW_cmp         | width=11   | u_PE3/gt_401 (PE.sv:401)   |
| gt_x_460       | DW_cmp         | width=11   | u_PE3/gt_401_2 (PE.sv:401) |
| add_x_461      | DW01_inc       | width=3    | u_PE3/add_464_S2 (PE.sv:464) |
| lt_x_483       | DW_cmp         | width=4    | u_CC/lt_193 (connection_check.sv:193) |
      |                |            | u_CC/lt_278 (connection_check.sv:278) |
| lt_x_484       | DW_cmp         | width=4    | u_CC/lt_194 (connection_check.sv:194) |
      |                |            | u_CC/lt_282 (connection_check.sv:282) |
| lt_x_485       | DW_cmp         | width=4    | u_CC/lt_195 (connection_check.sv:195) |
      |                |            | u_CC/lt_286 (connection_check.sv:286) |
| add_x_115      | DW01_inc       | width=6    | u_PE2/add_108_C289 (PE.sv:108) |
             |                |            | u_PE2/add_108_C294 (PE.sv:108) |
             |                |            | u_PE2/add_108_C299 (PE.sv:108) |
             |                |            | u_PE2/add_108_C309 (PE.sv:108) |
             |                |            | u_PE2/add_108_C319 (PE.sv:108) |
             |                |            | u_PE2/add_108_C324 (PE.sv:108) |
             |                |            | u_PE2/add_108_C334 (PE.sv:108) |
             |                |            | u_PE2/add_108_C339 (PE.sv:108) |
| add_x_410      | DW01_inc       | width=6    | u_PE3/add_108_C289 (PE.sv:108) |
             |                |            | u_PE3/add_108_C294 (PE.sv:108) |
             |                |            | u_PE3/add_108_C299 (PE.sv:108) |
             |                |            | u_PE3/add_108_C309 (PE.sv:108) |
             |                |            | u_PE3/add_108_C319 (PE.sv:108) |
             |                |            | u_PE3/add_108_C324 (PE.sv:108) |
             |                |            | u_PE3/add_108_C334 (PE.sv:108) |
             |                |            | u_PE3/add_108_C339 (PE.sv:108) |
| add_x_114      | DW01_inc       | width=6    | u_PE2/add_108_C288 (PE.sv:108) |
             |                |            | u_PE2/add_108_C303 (PE.sv:108) |
             |                |            | u_PE2/add_108_C308 (PE.sv:108) |
             |                |            | u_PE2/add_108_C313 (PE.sv:108) |
             |                |            | u_PE2/add_108_C318 (PE.sv:108) |
             |                |            | u_PE2/add_108_C328 (PE.sv:108) |
             |                |            | u_PE2/add_108_C338 (PE.sv:108) |
| add_x_116      | DW01_inc       | width=6    | u_PE2/add_108_C290 (PE.sv:108) |
             |                |            | u_PE2/add_108_C295 (PE.sv:108) |
             |                |            | u_PE2/add_108_C300 (PE.sv:108) |
             |                |            | u_PE2/add_108_C305 (PE.sv:108) |
             |                |            | u_PE2/add_108_C310 (PE.sv:108) |
             |                |            | u_PE2/add_108_C315 (PE.sv:108) |
             |                |            | u_PE2/add_108_C340 (PE.sv:108) |
| add_x_409      | DW01_inc       | width=6    | u_PE3/add_108_C288 (PE.sv:108) |
             |                |            | u_PE3/add_108_C303 (PE.sv:108) |
             |                |            | u_PE3/add_108_C308 (PE.sv:108) |
             |                |            | u_PE3/add_108_C313 (PE.sv:108) |
             |                |            | u_PE3/add_108_C318 (PE.sv:108) |
             |                |            | u_PE3/add_108_C328 (PE.sv:108) |
             |                |            | u_PE3/add_108_C338 (PE.sv:108) |
| add_x_411      | DW01_inc       | width=6    | u_PE3/add_108_C290 (PE.sv:108) |
             |                |            | u_PE3/add_108_C295 (PE.sv:108) |
             |                |            | u_PE3/add_108_C300 (PE.sv:108) |
             |                |            | u_PE3/add_108_C305 (PE.sv:108) |
             |                |            | u_PE3/add_108_C310 (PE.sv:108) |
             |                |            | u_PE3/add_108_C315 (PE.sv:108) |
             |                |            | u_PE3/add_108_C340 (PE.sv:108) |
| add_x_225      | DW01_inc       | width=2    | u_CC/add_122_I2 (connection_check.sv:122) |
  |                |            | u_CC/add_123_I2 (connection_check.sv:123) |
  |                |            | u_CC/add_223 (connection_check.sv:223) |
| add_x_26       | DW01_inc       | width=6    | u_PE0/add_108_C298 (PE.sv:108) |
             |                |            | u_PE0/add_108_C333 (PE.sv:108) |
| add_x_214      | DW01_inc       | width=4    | u_CC/add_108 (connection_check.sv:108) |
     |                |            | u_CC/add_275 (connection_check.sv:275) |
| add_x_321      | DW01_inc       | width=6    | u_PE1/add_108_C298 (PE.sv:108) |
             |                |            | u_PE1/add_108_C333 (PE.sv:108) |
| add_x_226      | DW01_add       | width=2    | u_CC/add_122_I3 (connection_check.sv:122) |
  |                |            | u_CC/add_123_I3 (connection_check.sv:123) |
| add_x_227      | DW01_dec       | width=2    | u_CC/add_122_I4 (connection_check.sv:122) |
  |                |            | u_CC/add_123_I4 (connection_check.sv:123) |
| gt_x_487       | DW_cmp         | width=6    | u_PE0/gt_110_C298 (PE.sv:110) |
              |                |            | u_PE0/gt_110_C333 (PE.sv:110) |
| gt_x_489       | DW_cmp         | width=6    | u_PE2/gt_110_C288 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C303 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C308 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C313 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C318 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C328 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C338 (PE.sv:110) |
| gt_x_491       | DW_cmp         | width=6    | u_PE2/gt_110_C289 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C294 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C299 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C309 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C319 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C324 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C334 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C339 (PE.sv:110) |
| gt_x_493       | DW_cmp         | width=6    | u_PE2/gt_110_C290 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C295 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C300 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C305 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C310 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C315 (PE.sv:110) |
              |                |            | u_PE2/gt_110_C340 (PE.sv:110) |
| gt_x_495       | DW_cmp         | width=6    | u_PE1/gt_110_C298 (PE.sv:110) |
              |                |            | u_PE1/gt_110_C333 (PE.sv:110) |
| gt_x_497       | DW_cmp         | width=6    | u_PE3/gt_110_C288 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C303 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C308 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C313 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C318 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C328 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C338 (PE.sv:110) |
| gt_x_499       | DW_cmp         | width=6    | u_PE3/gt_110_C289 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C294 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C299 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C309 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C319 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C324 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C334 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C339 (PE.sv:110) |
| gt_x_501       | DW_cmp         | width=6    | u_PE3/gt_110_C290 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C295 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C300 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C305 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C310 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C315 (PE.sv:110) |
              |                |            | u_PE3/gt_110_C340 (PE.sv:110) |
| DP_OP_1630J1_122_1529           |            |                            |
|                | DP_OP_1630J1_122_1529 |     |                            |
| DP_OP_1631J1_123_4500           |            |                            |
|                | DP_OP_1631J1_123_4500 |     |                            |
| DP_OP_1632J1_124_1975           |            |                            |
|                | DP_OP_1632J1_124_1975 |     |                            |
| DP_OP_1633J1_125_1975           |            |                            |
|                | DP_OP_1633J1_125_1975 |     |                            |
| DP_OP_1634J1_126_1975           |            |                            |
|                | DP_OP_1634J1_126_1975 |     |                            |
| DP_OP_1635J1_127_1975           |            |                            |
|                | DP_OP_1635J1_127_1975 |     |                            |
| DP_OP_1636J1_128_1975           |            |                            |
|                | DP_OP_1636J1_128_1975 |     |                            |
| DP_OP_1637J1_129_1975           |            |                            |
|                | DP_OP_1637J1_129_1975 |     |                            |
| DP_OP_1638J1_130_3747           |            |                            |
|                | DP_OP_1638J1_130_3747 |     |                            |
| DP_OP_1639J1_131_3747           |            |                            |
|                | DP_OP_1639J1_131_3747 |     |                            |
| DP_OP_1640J1_132_3746           |            |                            |
|                | DP_OP_1640J1_132_3746 |     |                            |
| DP_OP_1641J1_133_1529           |            |                            |
|                | DP_OP_1641J1_133_1529 |     |                            |
| DP_OP_1642J1_134_4500           |            |                            |
|                | DP_OP_1642J1_134_4500 |     |                            |
| DP_OP_1643J1_135_1975           |            |                            |
|                | DP_OP_1643J1_135_1975 |     |                            |
| DP_OP_1644J1_136_1975           |            |                            |
|                | DP_OP_1644J1_136_1975 |     |                            |
| DP_OP_1645J1_137_1975           |            |                            |
|                | DP_OP_1645J1_137_1975 |     |                            |
| DP_OP_1646J1_138_3747           |            |                            |
|                | DP_OP_1646J1_138_3747 |     |                            |
| DP_OP_1647J1_139_3747           |            |                            |
|                | DP_OP_1647J1_139_3747 |     |                            |
| DP_OP_1648J1_140_3746           |            |                            |
|                | DP_OP_1648J1_140_3746 |     |                            |
| DP_OP_1649J1_141_1529           |            |                            |
|                | DP_OP_1649J1_141_1529 |     |                            |
| DP_OP_1650J1_142_4500           |            |                            |
|                | DP_OP_1650J1_142_4500 |     |                            |
| DP_OP_1651J1_143_1975           |            |                            |
|                | DP_OP_1651J1_143_1975 |     |                            |
| DP_OP_1652J1_144_1975           |            |                            |
|                | DP_OP_1652J1_144_1975 |     |                            |
| DP_OP_1653J1_145_1975           |            |                            |
|                | DP_OP_1653J1_145_1975 |     |                            |
| DP_OP_1654J1_146_1975           |            |                            |
|                | DP_OP_1654J1_146_1975 |     |                            |
| DP_OP_1655J1_147_1975           |            |                            |
|                | DP_OP_1655J1_147_1975 |     |                            |
| DP_OP_1656J1_148_1975           |            |                            |
|                | DP_OP_1656J1_148_1975 |     |                            |
| DP_OP_1657J1_149_3747           |            |                            |
|                | DP_OP_1657J1_149_3747 |     |                            |
| DP_OP_1658J1_150_3747           |            |                            |
|                | DP_OP_1658J1_150_3747 |     |                            |
| DP_OP_1659J1_151_3746           |            |                            |
|                | DP_OP_1659J1_151_3746 |     |                            |
| DP_OP_1660J1_152_1529           |            |                            |
|                | DP_OP_1660J1_152_1529 |     |                            |
| DP_OP_1661J1_153_4500           |            |                            |
|                | DP_OP_1661J1_153_4500 |     |                            |
| DP_OP_1662J1_154_1975           |            |                            |
|                | DP_OP_1662J1_154_1975 |     |                            |
| DP_OP_1663J1_155_1975           |            |                            |
|                | DP_OP_1663J1_155_1975 |     |                            |
| DP_OP_1664J1_156_1975           |            |                            |
|                | DP_OP_1664J1_156_1975 |     |                            |
| DP_OP_1665J1_157_3747           |            |                            |
|                | DP_OP_1665J1_157_3747 |     |                            |
| DP_OP_1666J1_158_3747           |            |                            |
|                | DP_OP_1666J1_158_3747 |     |                            |
| DP_OP_1667J1_159_3746           |            |                            |
|                | DP_OP_1667J1_159_3746 |     |                            |
| DP_OP_442_272_5507              |            |                            |
|                | DP_OP_442_272_5507 |        |                            |
| DP_OP_443_273_5507              |            |                            |
|                | DP_OP_443_273_5507 |        |                            |
| DP_OP_444_276_726               |            |                            |
|                | DP_OP_444_276_726 |         |                            |
| DP_OP_445_277_726               |            |                            |
|                | DP_OP_445_277_726 |         |                            |
| DP_OP_554_258_3886              |            |                            |
|                | DP_OP_554_258_3886 |        |                            |
| DP_OP_555_259_3886              |            |                            |
|                | DP_OP_555_259_3886 |        |                            |
| DP_OP_550_268_1131              |            |                            |
|                | DP_OP_550_268_1131 |        |                            |
| DP_OP_551_269_1131              |            |                            |
|                | DP_OP_551_269_1131 |        |                            |
| DP_OP_446_274_3481              |            |                            |
|                | DP_OP_446_274_3481 |        |                            |
| DP_OP_447_275_3481              |            |                            |
|                | DP_OP_447_275_3481 |        |                            |
| DP_OP_1609_297_2651             |            |                            |
|                | DP_OP_1609_297_2651 |       |                            |
| DP_OP_1606_293_9863             |            |                            |
|                | DP_OP_1606_293_9863 |       |                            |
| DP_OP_1603_292_7108             |            |                            |
|                | DP_OP_1603_292_7108 |       |                            |
| DP_OP_1600_291_2199             |            |                            |
|                | DP_OP_1600_291_2199 |       |                            |
| DP_OP_1597_296_3704             |            |                            |
|                | DP_OP_1597_296_3704 |       |                            |
| DP_OP_1594_290_949              |            |                            |
|                | DP_OP_1594_290_949 |        |                            |
| DP_OP_1591_295_8161             |            |                            |
|                | DP_OP_1591_295_8161 |       |                            |
| DP_OP_1588_289_3300             |            |                            |
|                | DP_OP_1588_289_3300 |       |                            |
| DP_OP_1585_288_545              |            |                            |
|                | DP_OP_1585_288_545 |        |                            |
| DP_OP_1582_294_7757             |            |                            |
|                | DP_OP_1582_294_7757 |       |                            |
| DP_OP_1579_287_2635             |            |                            |
|                | DP_OP_1579_287_2635 |       |                            |
| DP_OP_1576_286_9847             |            |                            |
|                | DP_OP_1576_286_9847 |       |                            |
| DP_OP_751_262_78                |            |                            |
|                | DP_OP_751_262_78 |          |                            |
| DP_OP_752_263_78                |            |                            |
|                | DP_OP_752_263_78 |          |                            |
| DP_OP_747_270_5200              |            |                            |
|                | DP_OP_747_270_5200 |        |                            |
| DP_OP_748_271_5200              |            |                            |
|                | DP_OP_748_271_5200 |        |                            |
| DP_OP_743_280_6641              |            |                            |
|                | DP_OP_743_280_6641 |        |                            |
| DP_OP_744_281_6641              |            |                            |
|                | DP_OP_744_281_6641 |        |                            |
| DP_OP_546_284_6237              |            |                            |
|                | DP_OP_546_284_6237 |        |                            |
| DP_OP_547_285_6237              |            |                            |
|                | DP_OP_547_285_6237 |        |                            |
| DP_OP_223_278_2753              |            |                            |
|                | DP_OP_223_278_2753 |        |                            |
| DP_OP_224_279_2753              |            |                            |
|                | DP_OP_224_279_2753 |        |                            |
| DP_OP_219_256_9965              |            |                            |
|                | DP_OP_219_256_9965 |        |                            |
| DP_OP_220_257_9965              |            |                            |
|                | DP_OP_220_257_9965 |        |                            |
| DP_OP_215_260_5184              |            |                            |
|                | DP_OP_215_260_5184 |        |                            |
| DP_OP_216_261_5184              |            |                            |
|                | DP_OP_216_261_5184 |        |                            |
| DP_OP_26_264_6561               |            |                            |
|                | DP_OP_26_264_6561 |         |                            |
| DP_OP_27_265_6561               |            |                            |
|                | DP_OP_27_265_6561 |         |                            |
| DP_OP_22_282_3806               |            |                            |
|                | DP_OP_22_282_3806 |         |                            |
| DP_OP_23_283_3806               |            |                            |
|                | DP_OP_23_283_3806 |         |                            |
| DP_OP_18_266_1051               |            |                            |
|                | DP_OP_18_266_1051 |         |                            |
| DP_OP_19_267_1051               |            |                            |
|                | DP_OP_19_267_1051 |         |                            |
=============================================================================

Datapath Report for DP_OP_1630J1_122_1529
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1630J1_122_1529 | u_PE0/add_224 (PE.sv:224)                          |
|                      | u_PE0/add_224_2 (PE.sv:224)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 9     |                                          |
| I2    | PI   | Unsigned | 9     |                                          |
| I3    | PI   | Unsigned | 9     |                                          |
| O1    | PO   | Unsigned | 10    | I1 + I2 + I3 (PE.sv:224)                 |
==============================================================================

Datapath Report for DP_OP_1631J1_123_4500
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1631J1_123_4500 | u_PE0/add_253 (PE.sv:253) u_PE0/add_353 (PE.sv:353) |
                      | u_PE0/gte_253 (PE.sv:253)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| I2    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Unsigned | 5     | I1 + $unsigned(1'b1) ( PE.sv:253 PE.sv:353 ) |
| O2    | PO   | Unsigned | 1     | O1 >= I2 (PE.sv:253)                     |
==============================================================================

Datapath Report for DP_OP_1632J1_124_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1632J1_124_1975 | u_PE0/add_108_C288 (PE.sv:108)                     |
|                      | u_PE0/add_108_C303 (PE.sv:108)                      |
|                      | u_PE0/add_108_C308 (PE.sv:108)                      |
|                      | u_PE0/add_108_C313 (PE.sv:108)                      |
|                      | u_PE0/add_108_C318 (PE.sv:108)                      |
|                      | u_PE0/add_108_C328 (PE.sv:108)                      |
|                      | u_PE0/add_108_C338 (PE.sv:108)                      |
|                      | u_PE0/lt_109_C288 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C303 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C308 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C313 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C318 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C328 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C338 (PE.sv:109)                       |
|                      | u_PE0/gt_110_C288 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C303 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C308 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C313 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C318 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C328 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C338 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1633J1_125_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1633J1_125_1975 | u_PE0/add_108_C289 (PE.sv:108)                     |
|                      | u_PE0/add_108_C294 (PE.sv:108)                      |
|                      | u_PE0/add_108_C299 (PE.sv:108)                      |
|                      | u_PE0/add_108_C309 (PE.sv:108)                      |
|                      | u_PE0/add_108_C319 (PE.sv:108)                      |
|                      | u_PE0/add_108_C324 (PE.sv:108)                      |
|                      | u_PE0/add_108_C334 (PE.sv:108)                      |
|                      | u_PE0/add_108_C339 (PE.sv:108)                      |
|                      | u_PE0/lt_109_C289 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C294 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C299 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C309 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C319 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C324 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C334 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C339 (PE.sv:109)                       |
|                      | u_PE0/gt_110_C289 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C294 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C299 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C309 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C319 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C324 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C334 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C339 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1634J1_126_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1634J1_126_1975 | u_PE0/add_108_C290 (PE.sv:108)                     |
|                      | u_PE0/add_108_C295 (PE.sv:108)                      |
|                      | u_PE0/add_108_C300 (PE.sv:108)                      |
|                      | u_PE0/add_108_C305 (PE.sv:108)                      |
|                      | u_PE0/add_108_C310 (PE.sv:108)                      |
|                      | u_PE0/add_108_C315 (PE.sv:108)                      |
|                      | u_PE0/add_108_C340 (PE.sv:108)                      |
|                      | u_PE0/lt_109_C290 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C295 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C300 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C305 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C310 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C315 (PE.sv:109)                       |
|                      | u_PE0/lt_109_C340 (PE.sv:109)                       |
|                      | u_PE0/gt_110_C290 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C295 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C300 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C305 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C310 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C315 (PE.sv:110)                       |
|                      | u_PE0/gt_110_C340 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1635J1_127_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1635J1_127_1975 | u_PE0/add_108_C343 (PE.sv:108)                     |
|                      | u_PE0/lt_109_C343 (PE.sv:109)                       |
|                      | u_PE0/gt_110_C343 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1636J1_128_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1636J1_128_1975 | u_PE0/add_108_C344 (PE.sv:108)                     |
|                      | u_PE0/lt_109_C344 (PE.sv:109)                       |
|                      | u_PE0/gt_110_C344 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1637J1_129_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1637J1_129_1975 | u_PE0/add_108_C345 (PE.sv:108)                     |
|                      | u_PE0/lt_109_C345 (PE.sv:109)                       |
|                      | u_PE0/gt_110_C345 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1638J1_130_3747
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1638J1_130_3747 | u_PE0/sub_378 (PE.sv:378) u_PE0/sub_381 (PE.sv:381) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:378)                      |
| O2    | PO   | Signed   | 11    | $unsigned(1'b0) - O1 (PE.sv:381)         |
==============================================================================

Datapath Report for DP_OP_1639J1_131_3747
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1639J1_131_3747 | u_PE0/sub_379 (PE.sv:379) u_PE0/sub_382 (PE.sv:382) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:379)                      |
| O2    | PO   | Signed   | 11    | $unsigned(1'b0) - O1 (PE.sv:382)         |
==============================================================================

Datapath Report for DP_OP_1640J1_132_3746
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1640J1_132_3746 | u_PE0/sub_380 (PE.sv:380) u_PE0/sub_383 (PE.sv:383) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:380)                      |
| O2    | PO   | Signed   | 10    | $unsigned(1'b0) - O1 (PE.sv:383)         |
==============================================================================

Datapath Report for DP_OP_1641J1_133_1529
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1641J1_133_1529 | u_PE2/add_224 (PE.sv:224)                          |
|                      | u_PE2/add_224_2 (PE.sv:224)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 9     |                                          |
| I2    | PI   | Unsigned | 9     |                                          |
| I3    | PI   | Unsigned | 9     |                                          |
| O1    | PO   | Unsigned | 10    | I1 + I2 + I3 (PE.sv:224)                 |
==============================================================================

Datapath Report for DP_OP_1642J1_134_4500
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1642J1_134_4500 | u_PE2/add_253 (PE.sv:253) u_PE2/add_353 (PE.sv:353) |
                      | u_PE2/gte_253 (PE.sv:253)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| I2    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Unsigned | 5     | I1 + $unsigned(1'b1) ( PE.sv:253 PE.sv:353 ) |
| O2    | PO   | Unsigned | 1     | O1 >= I2 (PE.sv:253)                     |
==============================================================================

Datapath Report for DP_OP_1643J1_135_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1643J1_135_1975 | u_PE2/add_108_C298 (PE.sv:108)                     |
|                      | u_PE2/add_108_C333 (PE.sv:108)                      |
|                      | u_PE2/lt_109_C298 (PE.sv:109)                       |
|                      | u_PE2/lt_109_C333 (PE.sv:109)                       |
|                      | u_PE2/gt_110_C298 (PE.sv:110)                       |
|                      | u_PE2/gt_110_C333 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1644J1_136_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1644J1_136_1975 | u_PE2/add_108_C314 (PE.sv:108)                     |
|                      | u_PE2/lt_109_C314 (PE.sv:109)                       |
|                      | u_PE2/gt_110_C314 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1645J1_137_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1645J1_137_1975 | u_PE2/add_108_C335 (PE.sv:108)                     |
|                      | u_PE2/lt_109_C335 (PE.sv:109)                       |
|                      | u_PE2/gt_110_C335 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1646J1_138_3747
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1646J1_138_3747 | u_PE2/sub_378 (PE.sv:378) u_PE2/sub_381 (PE.sv:381) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:378)                      |
| O2    | PO   | Signed   | 11    | $unsigned(1'b0) - O1 (PE.sv:381)         |
==============================================================================

Datapath Report for DP_OP_1647J1_139_3747
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1647J1_139_3747 | u_PE2/sub_379 (PE.sv:379) u_PE2/sub_382 (PE.sv:382) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:379)                      |
| O2    | PO   | Signed   | 11    | $unsigned(1'b0) - O1 (PE.sv:382)         |
==============================================================================

Datapath Report for DP_OP_1648J1_140_3746
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1648J1_140_3746 | u_PE2/sub_380 (PE.sv:380) u_PE2/sub_383 (PE.sv:383) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:380)                      |
| O2    | PO   | Signed   | 10    | $unsigned(1'b0) - O1 (PE.sv:383)         |
==============================================================================

Datapath Report for DP_OP_1649J1_141_1529
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1649J1_141_1529 | u_PE1/add_224 (PE.sv:224)                          |
|                      | u_PE1/add_224_2 (PE.sv:224)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 9     |                                          |
| I2    | PI   | Unsigned | 9     |                                          |
| I3    | PI   | Unsigned | 9     |                                          |
| O1    | PO   | Unsigned | 10    | I1 + I2 + I3 (PE.sv:224)                 |
==============================================================================

Datapath Report for DP_OP_1650J1_142_4500
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1650J1_142_4500 | u_PE1/add_253 (PE.sv:253) u_PE1/add_353 (PE.sv:353) |
                      | u_PE1/gte_253 (PE.sv:253)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| I2    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Unsigned | 5     | I1 + $unsigned(1'b1) ( PE.sv:253 PE.sv:353 ) |
| O2    | PO   | Unsigned | 1     | O1 >= I2 (PE.sv:253)                     |
==============================================================================

Datapath Report for DP_OP_1651J1_143_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1651J1_143_1975 | u_PE1/add_108_C288 (PE.sv:108)                     |
|                      | u_PE1/add_108_C303 (PE.sv:108)                      |
|                      | u_PE1/add_108_C308 (PE.sv:108)                      |
|                      | u_PE1/add_108_C313 (PE.sv:108)                      |
|                      | u_PE1/add_108_C318 (PE.sv:108)                      |
|                      | u_PE1/add_108_C328 (PE.sv:108)                      |
|                      | u_PE1/add_108_C338 (PE.sv:108)                      |
|                      | u_PE1/lt_109_C288 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C303 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C308 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C313 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C318 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C328 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C338 (PE.sv:109)                       |
|                      | u_PE1/gt_110_C288 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C303 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C308 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C313 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C318 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C328 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C338 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1652J1_144_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1652J1_144_1975 | u_PE1/add_108_C289 (PE.sv:108)                     |
|                      | u_PE1/add_108_C294 (PE.sv:108)                      |
|                      | u_PE1/add_108_C299 (PE.sv:108)                      |
|                      | u_PE1/add_108_C309 (PE.sv:108)                      |
|                      | u_PE1/add_108_C319 (PE.sv:108)                      |
|                      | u_PE1/add_108_C324 (PE.sv:108)                      |
|                      | u_PE1/add_108_C334 (PE.sv:108)                      |
|                      | u_PE1/add_108_C339 (PE.sv:108)                      |
|                      | u_PE1/lt_109_C289 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C294 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C299 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C309 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C319 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C324 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C334 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C339 (PE.sv:109)                       |
|                      | u_PE1/gt_110_C289 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C294 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C299 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C309 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C319 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C324 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C334 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C339 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1653J1_145_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1653J1_145_1975 | u_PE1/add_108_C290 (PE.sv:108)                     |
|                      | u_PE1/add_108_C295 (PE.sv:108)                      |
|                      | u_PE1/add_108_C300 (PE.sv:108)                      |
|                      | u_PE1/add_108_C305 (PE.sv:108)                      |
|                      | u_PE1/add_108_C310 (PE.sv:108)                      |
|                      | u_PE1/add_108_C315 (PE.sv:108)                      |
|                      | u_PE1/add_108_C340 (PE.sv:108)                      |
|                      | u_PE1/lt_109_C290 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C295 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C300 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C305 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C310 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C315 (PE.sv:109)                       |
|                      | u_PE1/lt_109_C340 (PE.sv:109)                       |
|                      | u_PE1/gt_110_C290 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C295 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C300 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C305 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C310 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C315 (PE.sv:110)                       |
|                      | u_PE1/gt_110_C340 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1654J1_146_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1654J1_146_1975 | u_PE1/add_108_C343 (PE.sv:108)                     |
|                      | u_PE1/lt_109_C343 (PE.sv:109)                       |
|                      | u_PE1/gt_110_C343 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1655J1_147_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1655J1_147_1975 | u_PE1/add_108_C344 (PE.sv:108)                     |
|                      | u_PE1/lt_109_C344 (PE.sv:109)                       |
|                      | u_PE1/gt_110_C344 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1656J1_148_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1656J1_148_1975 | u_PE1/add_108_C345 (PE.sv:108)                     |
|                      | u_PE1/lt_109_C345 (PE.sv:109)                       |
|                      | u_PE1/gt_110_C345 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1657J1_149_3747
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1657J1_149_3747 | u_PE1/sub_378 (PE.sv:378) u_PE1/sub_381 (PE.sv:381) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:378)                      |
| O2    | PO   | Signed   | 11    | $unsigned(1'b0) - O1 (PE.sv:381)         |
==============================================================================

Datapath Report for DP_OP_1658J1_150_3747
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1658J1_150_3747 | u_PE1/sub_379 (PE.sv:379) u_PE1/sub_382 (PE.sv:382) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:379)                      |
| O2    | PO   | Signed   | 11    | $unsigned(1'b0) - O1 (PE.sv:382)         |
==============================================================================

Datapath Report for DP_OP_1659J1_151_3746
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1659J1_151_3746 | u_PE1/sub_380 (PE.sv:380) u_PE1/sub_383 (PE.sv:383) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:380)                      |
| O2    | PO   | Signed   | 10    | $unsigned(1'b0) - O1 (PE.sv:383)         |
==============================================================================

Datapath Report for DP_OP_1660J1_152_1529
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1660J1_152_1529 | u_PE3/add_224 (PE.sv:224)                          |
|                      | u_PE3/add_224_2 (PE.sv:224)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 9     |                                          |
| I2    | PI   | Unsigned | 9     |                                          |
| I3    | PI   | Unsigned | 9     |                                          |
| O1    | PO   | Unsigned | 10    | I1 + I2 + I3 (PE.sv:224)                 |
==============================================================================

Datapath Report for DP_OP_1661J1_153_4500
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1661J1_153_4500 | u_PE3/add_253 (PE.sv:253) u_PE3/add_353 (PE.sv:353) |
                      | u_PE3/gte_253 (PE.sv:253)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| I2    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Unsigned | 5     | I1 + $unsigned(1'b1) ( PE.sv:253 PE.sv:353 ) |
| O2    | PO   | Unsigned | 1     | O1 >= I2 (PE.sv:253)                     |
==============================================================================

Datapath Report for DP_OP_1662J1_154_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1662J1_154_1975 | u_PE3/add_108_C298 (PE.sv:108)                     |
|                      | u_PE3/add_108_C333 (PE.sv:108)                      |
|                      | u_PE3/lt_109_C298 (PE.sv:109)                       |
|                      | u_PE3/lt_109_C333 (PE.sv:109)                       |
|                      | u_PE3/gt_110_C298 (PE.sv:110)                       |
|                      | u_PE3/gt_110_C333 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1663J1_155_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1663J1_155_1975 | u_PE3/add_108_C314 (PE.sv:108)                     |
|                      | u_PE3/lt_109_C314 (PE.sv:109)                       |
|                      | u_PE3/gt_110_C314 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1664J1_156_1975
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1664J1_156_1975 | u_PE3/add_108_C335 (PE.sv:108)                     |
|                      | u_PE3/lt_109_C335 (PE.sv:109)                       |
|                      | u_PE3/gt_110_C335 (PE.sv:110)                       |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 6     | I1 + $signed(1'b1) (PE.sv:108)           |
| O2    | PO   | Signed   | 1     | O1 < $signed(1'b0) (PE.sv:109)           |
| O3    | PO   | Signed   | 1     | O1 > $signed(5'b01111) (PE.sv:110)       |
==============================================================================

Datapath Report for DP_OP_1665J1_157_3747
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1665J1_157_3747 | u_PE3/sub_378 (PE.sv:378) u_PE3/sub_381 (PE.sv:381) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:378)                      |
| O2    | PO   | Signed   | 11    | $unsigned(1'b0) - O1 (PE.sv:381)         |
==============================================================================

Datapath Report for DP_OP_1666J1_158_3747
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1666J1_158_3747 | u_PE3/sub_379 (PE.sv:379) u_PE3/sub_382 (PE.sv:382) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:379)                      |
| O2    | PO   | Signed   | 11    | $unsigned(1'b0) - O1 (PE.sv:382)         |
==============================================================================

Datapath Report for DP_OP_1667J1_159_3746
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1667J1_159_3746 | u_PE3/sub_380 (PE.sv:380) u_PE3/sub_383 (PE.sv:383) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:380)                      |
| O2    | PO   | Signed   | 10    | $unsigned(1'b0) - O1 (PE.sv:383)         |
==============================================================================

Datapath Report for DP_OP_442_272_5507
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_442_272_5507   | u_CC/sub_101_S2_C109 (connection_check.sv:101)      |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 8     | I1 - I2 (connection_check.sv:101)        |
==============================================================================

Datapath Report for DP_OP_443_273_5507
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_443_273_5507   | u_CC/sub_101_S2_2_C109 (connection_check.sv:101)    |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 8     | I1 - I2 (connection_check.sv:101)        |
==============================================================================

Datapath Report for DP_OP_444_276_726
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_444_276_726    | u_CC/sub_101_S2_C109_2 (connection_check.sv:101)    |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 8     | I1 - I2 (connection_check.sv:101)        |
==============================================================================

Datapath Report for DP_OP_445_277_726
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_445_277_726    | u_CC/sub_101_S2_2_C109_2 (connection_check.sv:101)  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 8     | I1 - I2 (connection_check.sv:101)        |
==============================================================================

Datapath Report for DP_OP_554_258_3886
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_554_258_3886   | u_PE1/sub_223 (PE.sv:223)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:223)                      |
==============================================================================

Datapath Report for DP_OP_555_259_3886
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_555_259_3886   | u_PE1/sub_223_2 (PE.sv:223)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:223)                      |
==============================================================================

Datapath Report for DP_OP_550_268_1131
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_550_268_1131   | u_PE1/sub_222 (PE.sv:222)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:222)                      |
==============================================================================

Datapath Report for DP_OP_551_269_1131
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_551_269_1131   | u_PE1/sub_222_2 (PE.sv:222)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:222)                      |
==============================================================================

Datapath Report for DP_OP_446_274_3481
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_446_274_3481   | u_CC/sub_101_S2_C109_3 (connection_check.sv:101)    |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 8     | I1 - I2 (connection_check.sv:101)        |
==============================================================================

Datapath Report for DP_OP_447_275_3481
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_447_275_3481   | u_CC/sub_101_S2_2_C109_3 (connection_check.sv:101)  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 8     | I1 - I2 (connection_check.sv:101)        |
==============================================================================

Datapath Report for DP_OP_1609_297_2651
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1609_297_2651  | u_PE3/add_442 (PE.sv:442) u_PE3/sub_443 (PE.sv:443) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 9     |                                          |
| I2    | PI   | Unsigned | 1     |                                          |
| O1    | PO   | Signed   | 9     | addsub(I1,1,I2) ( PE.sv:442 PE.sv:443 )  |
==============================================================================

Datapath Report for DP_OP_1606_293_9863
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1606_293_9863  | u_PE3/add_436 (PE.sv:436) u_PE3/sub_437 (PE.sv:437) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 9     |                                          |
| I2    | PI   | Unsigned | 1     |                                          |
| O1    | PO   | Signed   | 9     | addsub(I1,1,I2) ( PE.sv:436 PE.sv:437 )  |
==============================================================================

Datapath Report for DP_OP_1603_292_7108
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1603_292_7108  | u_PE3/add_430 (PE.sv:430) u_PE3/sub_431 (PE.sv:431) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 9     |                                          |
| I2    | PI   | Unsigned | 1     |                                          |
| O1    | PO   | Signed   | 9     | addsub(I1,1,I2) ( PE.sv:430 PE.sv:431 )  |
==============================================================================

Datapath Report for DP_OP_1600_291_2199
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1600_291_2199  | u_PE1/add_442 (PE.sv:442) u_PE1/sub_443 (PE.sv:443) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 9     |                                          |
| I2    | PI   | Unsigned | 1     |                                          |
| O1    | PO   | Signed   | 9     | addsub(I1,1,I2) ( PE.sv:442 PE.sv:443 )  |
==============================================================================

Datapath Report for DP_OP_1597_296_3704
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1597_296_3704  | u_PE1/add_436 (PE.sv:436) u_PE1/sub_437 (PE.sv:437) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 9     |                                          |
| I2    | PI   | Unsigned | 1     |                                          |
| O1    | PO   | Signed   | 9     | addsub(I1,1,I2) ( PE.sv:436 PE.sv:437 )  |
==============================================================================

Datapath Report for DP_OP_1594_290_949
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1594_290_949   | u_PE1/add_430 (PE.sv:430) u_PE1/sub_431 (PE.sv:431) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 9     |                                          |
| I2    | PI   | Unsigned | 1     |                                          |
| O1    | PO   | Signed   | 9     | addsub(I1,1,I2) ( PE.sv:430 PE.sv:431 )  |
==============================================================================

Datapath Report for DP_OP_1591_295_8161
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1591_295_8161  | u_PE2/add_442 (PE.sv:442) u_PE2/sub_443 (PE.sv:443) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 9     |                                          |
| I2    | PI   | Unsigned | 1     |                                          |
| O1    | PO   | Signed   | 9     | addsub(I1,1,I2) ( PE.sv:442 PE.sv:443 )  |
==============================================================================

Datapath Report for DP_OP_1588_289_3300
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1588_289_3300  | u_PE2/add_436 (PE.sv:436) u_PE2/sub_437 (PE.sv:437) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 9     |                                          |
| I2    | PI   | Unsigned | 1     |                                          |
| O1    | PO   | Signed   | 9     | addsub(I1,1,I2) ( PE.sv:436 PE.sv:437 )  |
==============================================================================

Datapath Report for DP_OP_1585_288_545
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1585_288_545   | u_PE2/add_430 (PE.sv:430) u_PE2/sub_431 (PE.sv:431) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 9     |                                          |
| I2    | PI   | Unsigned | 1     |                                          |
| O1    | PO   | Signed   | 9     | addsub(I1,1,I2) ( PE.sv:430 PE.sv:431 )  |
==============================================================================

Datapath Report for DP_OP_1582_294_7757
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1582_294_7757  | u_PE0/add_442 (PE.sv:442) u_PE0/sub_443 (PE.sv:443) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 9     |                                          |
| I2    | PI   | Unsigned | 1     |                                          |
| O1    | PO   | Signed   | 9     | addsub(I1,1,I2) ( PE.sv:442 PE.sv:443 )  |
==============================================================================

Datapath Report for DP_OP_1579_287_2635
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1579_287_2635  | u_PE0/add_436 (PE.sv:436) u_PE0/sub_437 (PE.sv:437) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 9     |                                          |
| I2    | PI   | Unsigned | 1     |                                          |
| O1    | PO   | Signed   | 9     | addsub(I1,1,I2) ( PE.sv:436 PE.sv:437 )  |
==============================================================================

Datapath Report for DP_OP_1576_286_9847
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1576_286_9847  | u_PE0/add_430 (PE.sv:430) u_PE0/sub_431 (PE.sv:431) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 9     |                                          |
| I2    | PI   | Unsigned | 1     |                                          |
| O1    | PO   | Signed   | 9     | addsub(I1,1,I2) ( PE.sv:430 PE.sv:431 )  |
==============================================================================

Datapath Report for DP_OP_751_262_78
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_751_262_78     | u_PE3/sub_223 (PE.sv:223)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:223)                      |
==============================================================================

Datapath Report for DP_OP_752_263_78
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_752_263_78     | u_PE3/sub_223_2 (PE.sv:223)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:223)                      |
==============================================================================

Datapath Report for DP_OP_747_270_5200
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_747_270_5200   | u_PE3/sub_222 (PE.sv:222)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:222)                      |
==============================================================================

Datapath Report for DP_OP_748_271_5200
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_748_271_5200   | u_PE3/sub_222_2 (PE.sv:222)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:222)                      |
==============================================================================

Datapath Report for DP_OP_743_280_6641
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_743_280_6641   | u_PE3/sub_221 (PE.sv:221)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:221)                      |
==============================================================================

Datapath Report for DP_OP_744_281_6641
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_744_281_6641   | u_PE3/sub_221_2 (PE.sv:221)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:221)                      |
==============================================================================

Datapath Report for DP_OP_546_284_6237
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_546_284_6237   | u_PE1/sub_221 (PE.sv:221)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:221)                      |
==============================================================================

Datapath Report for DP_OP_547_285_6237
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_547_285_6237   | u_PE1/sub_221_2 (PE.sv:221)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:221)                      |
==============================================================================

Datapath Report for DP_OP_223_278_2753
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_223_278_2753   | u_PE2/sub_223 (PE.sv:223)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:223)                      |
==============================================================================

Datapath Report for DP_OP_224_279_2753
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_224_279_2753   | u_PE2/sub_223_2 (PE.sv:223)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:223)                      |
==============================================================================

Datapath Report for DP_OP_219_256_9965
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_219_256_9965   | u_PE2/sub_222 (PE.sv:222)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:222)                      |
==============================================================================

Datapath Report for DP_OP_220_257_9965
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_220_257_9965   | u_PE2/sub_222_2 (PE.sv:222)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:222)                      |
==============================================================================

Datapath Report for DP_OP_215_260_5184
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_215_260_5184   | u_PE2/sub_221 (PE.sv:221)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:221)                      |
==============================================================================

Datapath Report for DP_OP_216_261_5184
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_216_261_5184   | u_PE2/sub_221_2 (PE.sv:221)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:221)                      |
==============================================================================

Datapath Report for DP_OP_26_264_6561
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_26_264_6561    | u_PE0/sub_223 (PE.sv:223)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:223)                      |
==============================================================================

Datapath Report for DP_OP_27_265_6561
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_27_265_6561    | u_PE0/sub_223_2 (PE.sv:223)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:223)                      |
==============================================================================

Datapath Report for DP_OP_22_282_3806
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_22_282_3806    | u_PE0/sub_222 (PE.sv:222)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:222)                      |
==============================================================================

Datapath Report for DP_OP_23_283_3806
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_23_283_3806    | u_PE0/sub_222_2 (PE.sv:222)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:222)                      |
==============================================================================

Datapath Report for DP_OP_18_266_1051
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_18_266_1051    | u_PE0/sub_221 (PE.sv:221)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:221)                      |
==============================================================================

Datapath Report for DP_OP_19_267_1051
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_19_267_1051    | u_PE0/sub_221_2 (PE.sv:221)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 (PE.sv:221)                      |
==============================================================================


Datapath Extraction Report

Information: Operator associated with resources 'u_CC/add_108 (connection_check.sv:108) u_CC/add_275 (connection_check.sv:275)' in design 'RRT_TOP' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'u_CC/gte_108 (connection_check.sv:108)'.  (HDL-120)

Information: Operator associated with resources 'u_CC/add_90_C97 (connection_check.sv:90)' in design 'RRT_TOP' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'u_CC/C1811 (connection_check.sv:90)'.  (HDL-120)

Information: Operator associated with resources 'u_CC/add_90_C96 (connection_check.sv:90)' in design 'RRT_TOP' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'u_CC/C1810 (connection_check.sv:90)'.  (HDL-120)

Information: Operator associated with resources 'u_CC/add_90_C95 (connection_check.sv:90)' in design 'RRT_TOP' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'u_CC/C1809 (connection_check.sv:90)'.  (HDL-120)


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| lt_x_10            | DW_cmp           | apparch (area)     |                |
| gt_x_14            | DW_cmp           | apparch (area)     |                |
| gt_x_15            | DW_cmp           | apparch (area)     |                |
| gt_x_16            | DW_cmp           | apparch (area)     |                |
| lt_x_17            | DW_cmp           | apparch (area)     |                |
| lt_x_24            | DW_cmp           | apparch (area)     |                |
| add_x_25           | DW01_inc         | apparch (area)     |                |
| add_x_27           | DW01_inc         | apparch (area)     |                |
| gt_x_29            | DW_cmp           | apparch (area)     |                |
| add_x_30           | DW01_inc         | apparch (area)     |                |
| gt_x_32            | DW_cmp           | apparch (area)     |                |
| gt_x_69            | DW_cmp           | apparch (area)     |                |
| lt_x_70            | DW_cmp           | apparch (area)     |                |
| gt_x_71            | DW_cmp           | apparch (area)     |                |
| gt_x_72            | DW_cmp           | apparch (area)     |                |
| add_x_73           | DW01_inc         | apparch (area)     |                |
| lt_x_98            | DW_cmp           | apparch (area)     |                |
| gt_x_102           | DW_cmp           | apparch (area)     |                |
| gt_x_103           | DW_cmp           | apparch (area)     |                |
| gt_x_104           | DW_cmp           | apparch (area)     |                |
| lt_x_105           | DW_cmp           | apparch (area)     |                |
| lt_x_112           | DW_cmp           | apparch (area)     |                |
| add_x_113          | DW01_inc         | apparch (area)     |                |
| add_x_117          | DW01_inc         | apparch (area)     |                |
| gt_x_119           | DW_cmp           | apparch (area)     |                |
| add_x_120          | DW01_inc         | apparch (area)     |                |
| gt_x_122           | DW_cmp           | apparch (area)     |                |
| add_x_123          | DW01_inc         | apparch (area)     |                |
| gt_x_125           | DW_cmp           | apparch (area)     |                |
| gt_x_162           | DW_cmp           | apparch (area)     |                |
| lt_x_163           | DW_cmp           | apparch (area)     |                |
| gt_x_164           | DW_cmp           | apparch (area)     |                |
| gt_x_165           | DW_cmp           | apparch (area)     |                |
| add_x_166          | DW01_inc         | apparch (area)     |                |
| sub_x_196          | DW01_dec         | apparch (area)     |                |
| gt_x_197           | DW_cmp           | apparch (area)     |                |
| sub_x_198          | DW01_sub         | apparch (area)     |                |
| gt_x_199           | DW_cmp           | apparch (area)     |                |
| sub_x_200          | DW01_sub         | apparch (area)     |                |
| gt_x_201           | DW_cmp           | apparch (area)     |                |
| sub_x_202          | DW01_sub         | apparch (area)     |                |
| lt_x_203           | DW_cmp           | apparch (area)     |                |
| add_x_204          | DW01_inc         | apparch (area)     |                |
| lt_x_206           | DW_cmp           | apparch (area)     |                |
| add_x_207          | DW01_inc         | apparch (area)     |                |
| lt_x_209           | DW_cmp           | apparch (area)     |                |
| add_x_210          | DW01_inc         | apparch (area)     |                |
| lt_x_213           | DW_cmp           | apparch (area)     |                |
| gte_x_215          | DW_cmp           | apparch (area)     |                |
| gte_x_216          | DW_cmp           | apparch (area)     |                |
| lte_x_217          | DW_cmp           | apparch (area)     |                |
| gte_x_218          | DW_cmp           | apparch (area)     |                |
| lte_x_219          | DW_cmp           | apparch (area)     |                |
| gte_x_220          | DW_cmp           | apparch (area)     |                |
| lte_x_221          | DW_cmp           | apparch (area)     |                |
| lt_x_236           | DW_cmp           | apparch (area)     |                |
| add_x_244          | DW01_inc         | apparch (area)     |                |
| add_x_246          | DW01_inc         | apparch (area)     |                |
| add_x_247          | DW01_inc         | apparch (area)     |                |
| add_x_248          | DW01_inc         | apparch (area)     |                |
| lt_x_305           | DW_cmp           | apparch (area)     |                |
| gt_x_309           | DW_cmp           | apparch (area)     |                |
| gt_x_310           | DW_cmp           | apparch (area)     |                |
| gt_x_311           | DW_cmp           | apparch (area)     |                |
| lt_x_312           | DW_cmp           | apparch (area)     |                |
| lt_x_319           | DW_cmp           | apparch (area)     |                |
| add_x_320          | DW01_inc         | apparch (area)     |                |
| add_x_322          | DW01_inc         | apparch (area)     |                |
| gt_x_324           | DW_cmp           | apparch (area)     |                |
| add_x_325          | DW01_inc         | apparch (area)     |                |
| gt_x_327           | DW_cmp           | apparch (area)     |                |
| gt_x_364           | DW_cmp           | apparch (area)     |                |
| lt_x_365           | DW_cmp           | apparch (area)     |                |
| gt_x_366           | DW_cmp           | apparch (area)     |                |
| gt_x_367           | DW_cmp           | apparch (area)     |                |
| add_x_368          | DW01_inc         | apparch (area)     |                |
| lt_x_393           | DW_cmp           | apparch (area)     |                |
| gt_x_397           | DW_cmp           | apparch (area)     |                |
| gt_x_398           | DW_cmp           | apparch (area)     |                |
| gt_x_399           | DW_cmp           | apparch (area)     |                |
| lt_x_400           | DW_cmp           | apparch (area)     |                |
| lt_x_407           | DW_cmp           | apparch (area)     |                |
| add_x_408          | DW01_inc         | apparch (area)     |                |
| add_x_412          | DW01_inc         | apparch (area)     |                |
| gt_x_414           | DW_cmp           | apparch (area)     |                |
| add_x_415          | DW01_inc         | apparch (area)     |                |
| gt_x_417           | DW_cmp           | apparch (area)     |                |
| add_x_418          | DW01_inc         | apparch (area)     |                |
| gt_x_420           | DW_cmp           | apparch (area)     |                |
| gt_x_457           | DW_cmp           | apparch (area)     |                |
| lt_x_458           | DW_cmp           | apparch (area)     |                |
| gt_x_459           | DW_cmp           | apparch (area)     |                |
| gt_x_460           | DW_cmp           | apparch (area)     |                |
| add_x_461          | DW01_inc         | apparch (area)     |                |
| lt_x_483           | DW_cmp           | apparch (area)     |                |
| lt_x_484           | DW_cmp           | apparch (area)     |                |
| lt_x_485           | DW_cmp           | apparch (area)     |                |
| add_x_115          | DW01_inc         | apparch (area)     |                |
| add_x_410          | DW01_inc         | apparch (area)     |                |
| add_x_114          | DW01_inc         | apparch (area)     |                |
| add_x_116          | DW01_inc         | apparch (area)     |                |
| add_x_409          | DW01_inc         | apparch (area)     |                |
| add_x_411          | DW01_inc         | apparch (area)     |                |
| add_x_225          | DW01_inc         | apparch (area)     |                |
| add_x_26           | DW01_inc         | apparch (area)     |                |
| add_x_214          | DW01_inc         | apparch (area)     |                |
| add_x_321          | DW01_inc         | apparch (area)     |                |
| add_x_226          | DW01_add         | apparch (area)     |                |
| add_x_227          | DW01_dec         | apparch (area)     |                |
| gt_x_487           | DW_cmp           | apparch (area)     |                |
| gt_x_489           | DW_cmp           | apparch (area)     |                |
| gt_x_491           | DW_cmp           | apparch (area)     |                |
| gt_x_493           | DW_cmp           | apparch (area)     |                |
| gt_x_495           | DW_cmp           | apparch (area)     |                |
| gt_x_497           | DW_cmp           | apparch (area)     |                |
| gt_x_499           | DW_cmp           | apparch (area)     |                |
| gt_x_501           | DW_cmp           | apparch (area)     |                |
| DP_OP_1630J1_122_1529                 |                    |                |
|                    | DP_OP_1630J1_122_1529 | str (area,speed)               |
| DP_OP_1631J1_123_4500                 |                    |                |
|                    | DP_OP_1631J1_123_4500 | str (area)    |                |
| DP_OP_1632J1_124_1975                 |                    |                |
|                    | DP_OP_1632J1_124_1975 | str (area)    |                |
| DP_OP_1633J1_125_1975                 |                    |                |
|                    | DP_OP_1633J1_125_1975 | str (area)    |                |
| DP_OP_1634J1_126_1975                 |                    |                |
|                    | DP_OP_1634J1_126_1975 | str (area)    |                |
| DP_OP_1635J1_127_1975                 |                    |                |
|                    | DP_OP_1635J1_127_1975 | str (area)    |                |
| DP_OP_1636J1_128_1975                 |                    |                |
|                    | DP_OP_1636J1_128_1975 | str (area)    |                |
| DP_OP_1637J1_129_1975                 |                    |                |
|                    | DP_OP_1637J1_129_1975 | str (area)    |                |
| DP_OP_1638J1_130_3747                 |                    |                |
|                    | DP_OP_1638J1_130_3747 | str (area,speed)               |
| DP_OP_1639J1_131_3747                 |                    |                |
|                    | DP_OP_1639J1_131_3747 | str (area,speed)               |
| DP_OP_1640J1_132_3746                 |                    |                |
|                    | DP_OP_1640J1_132_3746 | str (area,speed)               |
| DP_OP_1641J1_133_1529                 |                    |                |
|                    | DP_OP_1641J1_133_1529 | str (area,speed)               |
| DP_OP_1642J1_134_4500                 |                    |                |
|                    | DP_OP_1642J1_134_4500 | str (area)    |                |
| DP_OP_1643J1_135_1975                 |                    |                |
|                    | DP_OP_1643J1_135_1975 | str (area)    |                |
| DP_OP_1644J1_136_1975                 |                    |                |
|                    | DP_OP_1644J1_136_1975 | str (area)    |                |
| DP_OP_1645J1_137_1975                 |                    |                |
|                    | DP_OP_1645J1_137_1975 | str (area)    |                |
| DP_OP_1646J1_138_3747                 |                    |                |
|                    | DP_OP_1646J1_138_3747 | str (area,speed)               |
| DP_OP_1647J1_139_3747                 |                    |                |
|                    | DP_OP_1647J1_139_3747 | str (area,speed)               |
| DP_OP_1648J1_140_3746                 |                    |                |
|                    | DP_OP_1648J1_140_3746 | str (area,speed)               |
| DP_OP_1649J1_141_1529                 |                    |                |
|                    | DP_OP_1649J1_141_1529 | str (area,speed)               |
| DP_OP_1650J1_142_4500                 |                    |                |
|                    | DP_OP_1650J1_142_4500 | str (area)    |                |
| DP_OP_1651J1_143_1975                 |                    |                |
|                    | DP_OP_1651J1_143_1975 | str (area)    |                |
| DP_OP_1652J1_144_1975                 |                    |                |
|                    | DP_OP_1652J1_144_1975 | str (area)    |                |
| DP_OP_1653J1_145_1975                 |                    |                |
|                    | DP_OP_1653J1_145_1975 | str (area)    |                |
| DP_OP_1654J1_146_1975                 |                    |                |
|                    | DP_OP_1654J1_146_1975 | str (area)    |                |
| DP_OP_1655J1_147_1975                 |                    |                |
|                    | DP_OP_1655J1_147_1975 | str (area)    |                |
| DP_OP_1656J1_148_1975                 |                    |                |
|                    | DP_OP_1656J1_148_1975 | str (area)    |                |
| DP_OP_1657J1_149_3747                 |                    |                |
|                    | DP_OP_1657J1_149_3747 | str (area,speed)               |
| DP_OP_1658J1_150_3747                 |                    |                |
|                    | DP_OP_1658J1_150_3747 | str (area,speed)               |
| DP_OP_1659J1_151_3746                 |                    |                |
|                    | DP_OP_1659J1_151_3746 | str (area,speed)               |
| DP_OP_1660J1_152_1529                 |                    |                |
|                    | DP_OP_1660J1_152_1529 | str (area,speed)               |
| DP_OP_1661J1_153_4500                 |                    |                |
|                    | DP_OP_1661J1_153_4500 | str (area)    |                |
| DP_OP_1662J1_154_1975                 |                    |                |
|                    | DP_OP_1662J1_154_1975 | str (area)    |                |
| DP_OP_1663J1_155_1975                 |                    |                |
|                    | DP_OP_1663J1_155_1975 | str (area)    |                |
| DP_OP_1664J1_156_1975                 |                    |                |
|                    | DP_OP_1664J1_156_1975 | str (area)    |                |
| DP_OP_1665J1_157_3747                 |                    |                |
|                    | DP_OP_1665J1_157_3747 | str (area,speed)               |
| DP_OP_1666J1_158_3747                 |                    |                |
|                    | DP_OP_1666J1_158_3747 | str (area,speed)               |
| DP_OP_1667J1_159_3746                 |                    |                |
|                    | DP_OP_1667J1_159_3746 | str (area,speed)               |
| DP_OP_442_272_5507 | DP_OP_442_272_5507 | str (area,speed) |                |
| DP_OP_443_273_5507 | DP_OP_443_273_5507 | str (area,speed) |                |
| DP_OP_444_276_726  | DP_OP_444_276_726 | str (area,speed)  |                |
| DP_OP_445_277_726  | DP_OP_445_277_726 | str (area,speed)  |                |
| DP_OP_554_258_3886 | DP_OP_554_258_3886 | str (area,speed) |                |
| DP_OP_555_259_3886 | DP_OP_555_259_3886 | str (area,speed) |                |
| DP_OP_550_268_1131 | DP_OP_550_268_1131 | str (area,speed) |                |
| DP_OP_551_269_1131 | DP_OP_551_269_1131 | str (area,speed) |                |
| DP_OP_446_274_3481 | DP_OP_446_274_3481 | str (area,speed) |                |
| DP_OP_447_275_3481 | DP_OP_447_275_3481 | str (area,speed) |                |
| DP_OP_1609_297_2651                   |                    |                |
|                    | DP_OP_1609_297_2651 | str (area,speed)                 |
| DP_OP_1606_293_9863                   |                    |                |
|                    | DP_OP_1606_293_9863 | str (area,speed)                 |
| DP_OP_1603_292_7108                   |                    |                |
|                    | DP_OP_1603_292_7108 | str (area,speed)                 |
| DP_OP_1600_291_2199                   |                    |                |
|                    | DP_OP_1600_291_2199 | str (area,speed)                 |
| DP_OP_1597_296_3704                   |                    |                |
|                    | DP_OP_1597_296_3704 | str (area,speed)                 |
| DP_OP_1594_290_949 | DP_OP_1594_290_949 | str (area,speed) |                |
| DP_OP_1591_295_8161                   |                    |                |
|                    | DP_OP_1591_295_8161 | str (area,speed)                 |
| DP_OP_1588_289_3300                   |                    |                |
|                    | DP_OP_1588_289_3300 | str (area,speed)                 |
| DP_OP_1585_288_545 | DP_OP_1585_288_545 | str (area,speed) |                |
| DP_OP_1582_294_7757                   |                    |                |
|                    | DP_OP_1582_294_7757 | str (area,speed)                 |
| DP_OP_1579_287_2635                   |                    |                |
|                    | DP_OP_1579_287_2635 | str (area,speed)                 |
| DP_OP_1576_286_9847                   |                    |                |
|                    | DP_OP_1576_286_9847 | str (area,speed)                 |
| DP_OP_751_262_78   | DP_OP_751_262_78 | str (area,speed)   |                |
| DP_OP_752_263_78   | DP_OP_752_263_78 | str (area,speed)   |                |
| DP_OP_747_270_5200 | DP_OP_747_270_5200 | str (area,speed) |                |
| DP_OP_748_271_5200 | DP_OP_748_271_5200 | str (area,speed) |                |
| DP_OP_743_280_6641 | DP_OP_743_280_6641 | str (area,speed) |                |
| DP_OP_744_281_6641 | DP_OP_744_281_6641 | str (area,speed) |                |
| DP_OP_546_284_6237 | DP_OP_546_284_6237 | str (area,speed) |                |
| DP_OP_547_285_6237 | DP_OP_547_285_6237 | str (area,speed) |                |
| DP_OP_223_278_2753 | DP_OP_223_278_2753 | str (area,speed) |                |
| DP_OP_224_279_2753 | DP_OP_224_279_2753 | str (area,speed) |                |
| DP_OP_219_256_9965 | DP_OP_219_256_9965 | str (area,speed) |                |
| DP_OP_220_257_9965 | DP_OP_220_257_9965 | str (area,speed) |                |
| DP_OP_215_260_5184 | DP_OP_215_260_5184 | str (area,speed) |                |
| DP_OP_216_261_5184 | DP_OP_216_261_5184 | str (area,speed) |                |
| DP_OP_26_264_6561  | DP_OP_26_264_6561 | str (area,speed)  |                |
| DP_OP_27_265_6561  | DP_OP_27_265_6561 | str (area,speed)  |                |
| DP_OP_22_282_3806  | DP_OP_22_282_3806 | str (area,speed)  |                |
| DP_OP_23_283_3806  | DP_OP_23_283_3806 | str (area,speed)  |                |
| DP_OP_18_266_1051  | DP_OP_18_266_1051 | str (area,speed)  |                |
| DP_OP_19_267_1051  | DP_OP_19_267_1051 | str (area,speed)  |                |
===============================================================================

1
